#!/bin/bash
./testall.sh "*5k.csv"
./testall.sh "*10k.csv"
./testall.sh "*25k.csv"
./testall.sh "*50k.csv"
./testall.sh "*75k.csv"
./testall.sh "*100k.csv"
./testall.sh "*150k.csv"
#./testall.sh "*200k.csv"
#./testall.sh "*250k.csv"
