version: '2.0'
services:
 graphModeling:
  image: neo4j:latest
  container_name: neo4j_graphModeling
  volumes:
   - ./import:/var/lib/neo4j/import
   - ./neo4j_conf:/var/lib/neo4j/conf
   - ./docker_folder:/root
  ports:
   - 7474:7474
   - 7687:7687
  environment:
   NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
   NEO4J_AUTH: neo4j/admin
