#!/bin/bash
#sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_5k.csv"
#sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_10k.csv"
#sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_25k.csv"
#sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_50k.csv"
#sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_75k.csv"
sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_100k.csv"
sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_150k.csv"
sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_200k.csv"
sudo docker exec -it neo4j_graphModeling bash -c "/root/testall.sh *_250k.csv"
