//indices
CREATE INDEX IF NOT EXISTS FOR (c:Concept) ON c.ID;
CREATE INDEX IF NOT EXISTS FOR (c:Concept) ON c.name;
CREATE INDEX IF NOT EXISTS FOR (t:TF) ON t.ID;
CREATE INDEX IF NOT EXISTS FOR (t:TF) ON t.date_start;
CREATE INDEX IF NOT EXISTS FOR (t:TF) ON t.date_end;
CREATE INDEX IF NOT EXISTS FOR (t:TF) ON t.polarity;
CREATE INDEX IF NOT EXISTS FOR (t:TF) ON t.s;
CREATE INDEX IF NOT EXISTS FOR (t:TF) ON t.o;
CREATE INDEX IF NOT EXISTS FOR (t:TF) ON t.p;